import React, { useState } from 'react'
import { Activity, ArrowLeft, ArrowRight, ArrowUpRight, Banknote, BarChart3, Bell, Building2, CalendarDays, Check, ChevronDown, ChevronLeft, ChevronRight, CircleDollarSign, ClipboardList, CloudUpload, Download, Edit3, Eye, FileCheck2, FileText, Filter, Home, Landmark, LayoutDashboard, Menu, MoreHorizontal, Pencil, Plus, ReceiptText, RefreshCw, Search, Settings, Sparkles, Table2, Trash2, TrendingUp, Upload, UserRound, Users, Wallet, WalletCards, Wrench, X, Zap } from 'lucide-react'
import { Page } from '../types'
import { buildings, investors, tenants, rentRows, sourceRows, renewalData } from '../data'
import { PageHeader, Toolbar, TableWrap, TableHead, Th, Pagination, Status } from '../shared'

export function AgreementsPage({onDraft}:{onDraft:(name:string)=>void}) {return <div className="page-stack"><PageHeader title="Contract Agreements" subtitle="Create, maintain and generate agreement templates." action={<button className="secondary-btn"><Download size={16}/> Export</button>}/><div className="panel"><Toolbar query="" setQuery={()=>{}}/><TableWrap><TableHead><Th>Agreement type</Th><Th>Template status</Th><Th>Last updated</Th><Th>Actions</Th></TableHead><tbody>{['Building Agreement','Tenant Agreement'].map((name,i)=><tr key={name}><td><div className="table-title"><span className="doc-icon"><FileText size={16}/></span><div><b>{name}</b><small>{i===0?'Property tenancy master agreement':'Tenant lease agreement'}</small></div></div></td><td><span className="badge green">Draft template</span></td><td>05 Oct 2026</td><td><button className="template-btn" onClick={()=>onDraft(name)}><Pencil size={14}/> Draft Template</button></td></tr>)}</tbody></TableWrap><Pagination total={2}/></div></div>}

export function AgreementEditor({name,onBack}:{name:string;onBack:()=>void}) {const tags=['[OrganizationName]','[TenantName]','[OwnerName]','[ContractStartDate]','[ContractEndDate]','[ContractYear]','[ContractMonth]','[ContractDays]','[MonthlyRent]','[SecurityDeposit]','[W&E_Deposit]','[MaintenanceDeposit]','[Miscellaneous]','[Others]','[CurrentDate]']; const [content,setContent]=useState(`AGREEMENT\n\nParty 1: [OrganizationName]\nParty 2: [OwnerName]\n\nSubject: Agreement of tenancy contract between [OrganizationName] and [OwnerName] as per the details provided below.\n\nContract start date: [ContractStartDate]\nContract end date: [ContractEndDate]\n\nContract term:\nYear: [ContractYear]\nMonth: [ContractMonth]\nDays: [ContractDays]\n\nDeposit Type:\nMonthly Rent amount: [MonthlyRent]\nSecurity Deposit: [SecurityDeposit]\nW&E Deposit: [W&E_Deposit]\nMaintenance Deposit: [MaintenanceDeposit]\nMiscellaneous: [Miscellaneous]\nOthers: [Others]\n\nThis is a tenancy contract obliged by both the parties.\n\nName: [OrganizationName]                         Name: [OwnerName]\nDate: [CurrentDate]                              Date: [CurrentDate]\nSignature:                                      Signature:`); return <div className="page-stack"><div className="editor-top"><button className="back-btn" onClick={onBack}><ArrowLeft size={16}/> Back to agreements</button><div><span className="badge blue">Draft</span><b>{name}</b></div><button className="primary-btn"><Check size={17}/> Save template</button></div><div className="editor-layout"><section className="panel editor-panel"><div className="editor-title"><div><div className="eyebrow">TEMPLATE BUILDER</div><h2>{name}</h2></div><select className="select-lg" value={name} onChange={()=>{}}><option>{name}</option><option>Tenant Agreement</option><option>Building Agreement</option></select></div><div className="editor-toolbar"><button><b>B</b></button><button><u>U</u></button><button><i>I</i></button><span/><button>• List</button><button>1. List</button><button>≡ Align</button><button>↗ Link</button><button>▦ Table</button></div><textarea className="agreement-editor" value={content} onChange={e=>setContent(e.target.value)}/><div className="editor-foot"><span><Check size={14}/> Autosaved just now</span><span>{content.length} characters</span></div></section><aside className="panel tag-panel"><div className="tag-header"><div><h2>Agreement Tags</h2><p>Click a tag to insert it into the template.</p></div><Sparkles size={18}/></div><div className="tag-list">{tags.map(tag=><button key={tag} onClick={()=>setContent(c=>c+' '+tag)}>{tag}<Plus size={13}/></button>)}</div><div className="tip"><Sparkles size={16}/><div><b>Smart placeholders</b><p>Tags are replaced automatically when an agreement is generated.</p></div></div></aside></div></div>}
