import React, { useState } from 'react'
import { Activity, ArrowLeft, ArrowRight, ArrowUpRight, Banknote, BarChart3, Bell, Building2, CalendarDays, Check, ChevronDown, ChevronLeft, ChevronRight, CircleDollarSign, ClipboardList, CloudUpload, Download, Edit3, Eye, FileCheck2, FileText, Filter, Home, Landmark, LayoutDashboard, Menu, MoreHorizontal, Pencil, Plus, ReceiptText, RefreshCw, Search, Settings, Sparkles, Table2, Trash2, TrendingUp, Upload, UserRound, Users, Wallet, WalletCards, Wrench, X, Zap } from 'lucide-react'
import { Page } from '../types'
import { buildings, investors, tenants, rentRows, sourceRows, renewalData } from '../data'
import { PageHeader, Toolbar, TableWrap, TableHead, Th, Pagination, Status } from '../shared'
import { Field, FormCard } from './BuildingsPage'

export function BankDetailsPage(){return <div className="page-stack"><PageHeader title="Bank Details" subtitle="Maintain bank accounts and settlement information."/><div className="form-stack"><FormCard title="Bank details" icon={<Landmark/>}><div className="form-grid three"><Field label="Organization" required type="select" value="Axiom"/><Field label="Account Number" required/><Field label="Account Name" required/><Field label="Account Type" required type="select" value="Current Account"/><Field label="IBAN Code"/><Field label="Swift Code"/><Field label="Bank Name" required/><Field label="Branch"/><Field label="Bank Code" value="BNK000003"/><Field label="IFSC Code"/><Field label="MICR Code"/><Field label="Address" textarea/><Field label="Country" type="select" value="Qatar"/><Field label="Contact Name"/><Field label="Contact Number"/><Field label="Contact Email"/></div></FormCard><div className="inline-actions bottom-actions"><button className="secondary-btn">Cancel</button><button className="primary-btn"><Check size={16}/> Save</button><button className="secondary-btn">Return</button></div></div></div>}

export function FinancialPage(){return <div className="page-stack"><PageHeader title="Financial" subtitle="Track monthly receipts, payments and account balances."/><div className="panel"><div className="filters"><Field label="Organization" type="select" value="Axiom"/><Field label="Year" type="select" value="2026"/><Field label="Month" type="select" value="October"/><Field label="Payment Method" type="select" placeholder="— Select —"/><Field label="Bank Details" type="select" placeholder="— Select All —"/><button className="primary-btn export-btn"><Download size={16}/> Export</button></div><TableWrap><TableHead><Th>Source</Th><Th>Description</Th><Th>Post/Pay by</Th><Th>Amount</Th><Th>DB / CR</Th><Th>Currency</Th><Th>Bank details</Th></TableHead><tbody><tr><td colSpan={3} className="total-label">Total Balance</td><td><b>0.00</b></td><td>—</td><td>QAR</td><td>—</td></tr></tbody></TableWrap></div></div>}
