import React, { useState } from 'react'
import { Activity, ArrowLeft, ArrowRight, ArrowUpRight, Banknote, BarChart3, Bell, Building2, CalendarDays, Check, ChevronDown, ChevronLeft, ChevronRight, CircleDollarSign, ClipboardList, CloudUpload, Download, Edit3, Eye, FileCheck2, FileText, Filter, Home, Landmark, LayoutDashboard, Menu, MoreHorizontal, Pencil, Plus, ReceiptText, RefreshCw, Search, Settings, Sparkles, Table2, Trash2, TrendingUp, Upload, UserRound, Users, Wallet, WalletCards, Wrench, X, Zap } from 'lucide-react'
import { Page } from '../types'
import { buildings, investors, tenants, rentRows, sourceRows, renewalData } from '../data'
import { PageHeader, Toolbar, TableWrap, TableHead, Th, Pagination, Status } from '../shared'
import { Field, FormCard } from './BuildingsPage'

export function SourcesPage({onEdit,onAdd}:{onEdit:(r:any)=>void;onAdd:()=>void}){return <div className="page-stack"><PageHeader title="Credit / Debit Sources" subtitle="Configure the transaction sources used throughout financial records." action={<button className="primary-btn" onClick={onAdd}><Plus size={17}/> Add source</button>}/><div className="panel"><Toolbar query="" setQuery={()=>{}}/><TableWrap><TableHead><Th>Item code</Th><Th>Description</Th><Th>Status</Th><Th>Date</Th><Th>Actions</Th></TableHead><tbody>{sourceRows.map(r=><tr key={r.code}><td><b>{r.code}</b></td><td>{r.description}</td><td><select className="inline-select" defaultValue={r.status}><option>Active</option><option>Inactive</option></select></td><td>{r.date}</td><td><button className="edit-btn" onClick={()=>onEdit(r)}><Pencil size={14}/> Edit</button></td></tr>)}</tbody></TableWrap><Pagination total={5}/></div></div>}

export function SourceModal({value,onClose,onSave}:{value:any;onClose:()=>void;onSave:()=>void}){return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><span className="eyebrow">FINANCIAL MASTER</span><h2>{value.code==='NEW'?'Add source':'Update source'}</h2></div><button onClick={onClose}><X/></button></div><div className="modal-body"><Field label="Description" value={value.description} textarea/><Field label="Status" type="select" value={value.status}/></div><div className="modal-foot"><button className="secondary-btn" onClick={onClose}>Close</button><button className="primary-btn" onClick={onSave}><Check size={16}/> Save</button></div></div></div>}

export function ConfirmModal({onClose}:{onClose:()=>void}){return <div className="modal-backdrop"><div className="modal small"><div className="modal-head"><h2>Delete record?</h2><button onClick={onClose}><X/></button></div><div className="modal-body"><p>This action cannot be undone. Please confirm that you want to continue.</p></div><div className="modal-foot"><button className="secondary-btn" onClick={onClose}>Cancel</button><button className="danger-btn">Delete</button></div></div></div>}
